import type { LocalFormDefinition } from "./types";
import { stateOptions } from "./cover-page";

const yesNoUnknownOptions = ["Yes", "No", "Unknown"];
const yesNoNaOptions = ["Yes", "No", "N/A"];
const conditionOptions = ["Excellent", "Good", "Average", "Fair", "Poor", "Damaged", "N/A - Not Applicable", "Unknown / Not Inspected"];
const associationVisible = { fieldId: "hasAssociation", values: ["Yes"] };

export const vacantLandSiteDataForm: LocalFormDefinition = {
  id: "vacant-land-site-data",
  title: "Vacant Land Site Data",
  category: "Property Condition Report (PCR)",
  description: "Vacant lot identity, site characteristics, utilities, environmental feasibility, public records, and observed site condition.",
  fields: [
    { id: "generalInfoDivider", label: "General Property Info", kind: "divider", placeholder: "Identify the vacant lot and confirm the report is tied to the correct parcel." },
    { id: "parcelId", label: "Parcel ID (PIN/BRT/OPA)", kind: "text", placeholder: "e.g., 88-123-4567 or 123456789" },
    { id: "lotParcelNumber", label: "Lot / Parcel #", kind: "text", placeholder: "Lot/Parcel" },
    { id: "propertyAddress", label: "Property Address", kind: "text", required: true, placeholder: "123 Main St" },
    { id: "propertyUnit", label: "Unit #", kind: "text", placeholder: "Unit 2B" },
    { id: "propertyCity", label: "City / Town", kind: "text", required: true },
    { id: "propertyState", label: "State", kind: "select", required: true, options: stateOptions },
    { id: "propertyZip", label: "ZIP Code", kind: "text", required: true, placeholder: "19104" },
    { id: "county", label: "County", kind: "text" },
    { id: "schoolDistrict", label: "School District", kind: "text" },
    {
      id: "propertyType",
      label: "Vacant Land / Lot Type",
      kind: "select",
      required: true,
      options: [
        "Residential Lot (Single-Family)",
        "Multifamily Lot (2-4 Units)",
        "Condominium Lot / Pad Site",
        "Planned Unit Development (PUD) Lot",
        "Commercial Lot",
        "Mixed-Use Lot",
        "Industrial Lot",
        "Agricultural / Farm Land",
        "Rural / Vacant Land",
        "Corner Lot",
        "Interior Lot",
        "Cul-de-sac Lot",
        "Flag Lot",
        "Irregular Lot",
        "Waterfront Lot",
        "Improved Lot (utilities present)",
        "Unimproved Lot (raw land)",
        "Buildable Lot",
        "Non-Buildable Lot",
        "Subdividable Lot"
      ]
    },
    {
      id: "ownershipType",
      label: "Ownership Type",
      kind: "select",
      required: true,
      options: [
        "Fee Simple (Full Ownership)",
        "Fee Simple - Subject to HOA",
        "Condominium Ownership",
        "Cooperative (Co-Op) Ownership",
        "Leasehold (Ground Lease / Long-Term Lease)",
        "Partial Interest / Fractional Ownership",
        "Life Estate",
        "Unknown"
      ]
    },
    {
      id: "currentUseStatus",
      label: "Current Use Status",
      kind: "select",
      required: true,
      options: [
        "Vacant Land (no active use)",
        "Idle / Abandoned (previous use but currently unused)",
        "Single-Family Residence",
        "Multifamily Residence (2-4 units)",
        "Apartment Building (5+ units)",
        "Manufactured / Mobile Home Use",
        "Retail Use",
        "Office Use",
        "Mixed-Use Occupancy",
        "Industrial / Warehouse Use",
        "Community / Institutional Use",
        "Government / Public Utility Use",
        "Open Space / Conservation / Wetlands",
        "Parking Lot Use",
        "Under Development / Construction",
        "Active Farming / Cropland",
        "Pasture / Livestock Use",
        "Timber / Forestry Use",
        "Recreational Use",
        "Other / Restricted"
      ]
    },
    { id: "legalDescription", label: "Legal Description", kind: "textarea", placeholder: "Enter legal description if known." },

    { id: "siteCharacteristicsDivider", label: "Site Characteristics", kind: "divider", placeholder: "Document physical lot attributes that affect utility, feasibility, and value." },
    { id: "siteSource", label: "Site Data Source", kind: "select", options: ["Public Records", "Assessment", "MLS Record", "Client Provided", "Self Inspection", "Other", "Unknown"], fullWidth: true },
    { id: "lotSize", label: "Lot Size (Sq Ft or Acres)", kind: "text", placeholder: "e.g., 10,000 sq ft or 0.25 acres" },
    { id: "frontageDepth", label: "Frontage / Depth", kind: "text", placeholder: "e.g., 20 ft x 100 ft" },
    { id: "lotShape", label: "Lot Shape", kind: "select", options: ["Rectangular/Square (Ideal)", "Irregular/Pie-shaped (Less Ideal)", "Flag Lot (Restricted access)", "Corner Lot", "Unknown / Not Assessed"] },
    { id: "topography", label: "Topography", kind: "select", options: ["Flat/Level", "Gently Sloped", "Steeply Sloped", "Hilly/Uneven", "Low-lying (Requires fill)", "Unknown / Not Assessed"] },
    { id: "zoning", label: "Zoning", kind: "text", placeholder: "e.g., RSA-5" },
    { id: "useConsistent", label: "Use Consistent with Zoning?", kind: "select", options: ["Yes", "No", "Unknown"] },
    { id: "useConsistentExplain", label: "Use / Zoning Inconsistency Explanation", kind: "textarea", placeholder: "Explain if current use appears inconsistent with zoning." },
    { id: "siteInspectionSummary", label: "Site Inspection Summary", kind: "textarea", placeholder: "Easements, encroachments, site influences, proximity to amenities, traffic, etc." },

    { id: "utilityDivider", label: "Utility Availability", kind: "divider", placeholder: "Record utilities known to be available at or near the lot line." },
    { id: "powerAvailability", label: "Power", kind: "checkboxes", options: ["Electricity available", "Renewable energy only", "Backup power only", "Not available", "Unknown / Not Assessed"] },
    { id: "gasAvailability", label: "Gas / Heating Utility", kind: "checkboxes", options: ["Natural Gas", "Propane", "Fuel Oil", "Electric HVAC", "Geothermal", "Not available", "Unknown / Not Assessed"] },
    { id: "waterAvailability", label: "Water Supply", kind: "checkboxes", options: ["Public/Municipal Water", "Private Well", "Shared/Community System", "Irrigation Water", "Rainwater Harvesting / Cistern", "Not available", "Unknown / Not Assessed"] },
    { id: "wastewaterAvailability", label: "Wastewater Disposal", kind: "checkboxes", options: ["Public Sewer", "Private Septic System", "Holding Tank", "Greywater Recycling System", "Not available", "Unknown / Not Assessed"] },
    { id: "communicationsAvailability", label: "Communications", kind: "checkboxes", options: ["Landline Telephone", "Internet", "Cable TV", "Cellular Coverage", "Multiple services available", "Not available", "Unknown / Not Assessed"] },
    { id: "drainageAvailability", label: "Drainage / Environmental Systems", kind: "checkboxes", options: ["Stormwater Drainage", "Irrigation/Drainage Canals", "Retention Ponds / Rainwater Capture", "No visible drainage system", "Unknown / Not Assessed"] },
    { id: "municipalServices", label: "Municipal / Community Services", kind: "checkboxes", options: ["Solid Waste Disposal", "Street Lighting", "Fire Hydrant / Protection", "Multiple services available", "Not available", "Unknown / Not Assessed"] },
    { id: "utilities", label: "Utility Notes", kind: "textarea", placeholder: "Utility mix, distance, cost, hookup concerns, special needs, etc." },

    { id: "hasAssociation", label: "Is this lot part of an HOA / Condo / Cooperative community?", kind: "select", required: true, options: yesNoUnknownOptions },
    { id: "associationDivider", label: "Association and Common Area Information", kind: "divider", placeholder: "Use when the vacant lot is subject to an HOA, condominium, cooperative, or shared common area arrangement.", visibleWhen: associationVisible },
    { id: "associationName", label: "Association / Cooperative Name", kind: "text", visibleWhen: associationVisible },
    { id: "seniorOnlyCommunity", label: "Senior-Only Community", kind: "select", options: yesNoUnknownOptions, visibleWhen: associationVisible },
    { id: "associationAddress", label: "Association Address", kind: "text", placeholder: "e.g., 123 Main St, Suite 200", visibleWhen: associationVisible },
    { id: "associationPhone", label: "Association Phone Number", kind: "text", placeholder: "e.g., (215) 555-1234", visibleWhen: associationVisible },
    { id: "associationFeeAmount", label: "Association / Condo Fee", kind: "text", placeholder: "e.g., $425", visibleWhen: associationVisible },
    { id: "associationFeeFrequency", label: "Fee Paid", kind: "select", options: ["Monthly", "Quarterly", "Yearly", "Unknown"], visibleWhen: associationVisible },
    { id: "associationFeeIncludes", label: "Fee Includes", kind: "text", placeholder: "e.g., Water, Sewer, Trash, Exterior Maintenance", visibleWhen: associationVisible },
    { id: "associationAmenities", label: "Common Amenities", kind: "text", placeholder: "e.g., parking, pool, clubhouse, trails", visibleWhen: associationVisible },
    { id: "associationNotes", label: "Association / Cooperative Summary", kind: "textarea", visibleWhen: associationVisible },

    { id: "commonAreaInspectionDivider", label: "Common Area Inspection", kind: "divider", placeholder: "Assess shared areas and amenities when visible from public/common access or otherwise available for inspection.", visibleWhen: associationVisible },
    { id: "commonAreaOverallCondition", label: "Overall Condition of Common Areas and Amenities", kind: "select", options: conditionOptions, fullWidth: true, visibleWhen: associationVisible },
    { id: "commonAreasCondition", label: "Common Areas", kind: "select", options: conditionOptions, visibleWhen: associationVisible },
    { id: "commonAreasNotes", label: "Common Area Notes", kind: "textarea", placeholder: "Lobbies, corridors, clubhouse, mailroom, courtyard, trails, etc.", visibleWhen: associationVisible },
    { id: "parkingAreaCondition", label: "Parking Area", kind: "select", options: conditionOptions, visibleWhen: associationVisible },
    { id: "parkingAreaNotes", label: "Parking Area Notes", kind: "textarea", placeholder: "Lot/garage condition, striping, lighting, access, signage.", visibleWhen: associationVisible },
    { id: "poolAreaCondition", label: "Pool Area", kind: "select", options: conditionOptions, visibleWhen: associationVisible },
    { id: "poolAreaNotes", label: "Pool Area Notes", kind: "textarea", placeholder: "Fencing, deck surface, visible maintenance; leave blank if not applicable.", visibleWhen: associationVisible },
    { id: "extraAmenitiesCondition", label: "Extra Amenities", kind: "select", options: conditionOptions, visibleWhen: associationVisible },
    { id: "extraAmenitiesNotes", label: "Extra Amenities Notes", kind: "textarea", placeholder: "Gym, community room, playground, courtyard, trails, etc.", visibleWhen: associationVisible },
    { id: "elevatorCondition", label: "Elevator", kind: "select", options: conditionOptions, visibleWhen: associationVisible },
    { id: "elevatorNotes", label: "Elevator Notes", kind: "textarea", placeholder: "Call panel condition, signage, visible condition, or not applicable.", visibleWhen: associationVisible },
    { id: "securityCondition", label: "Security", kind: "select", options: conditionOptions, visibleWhen: associationVisible },
    { id: "securityNotes", label: "Security Notes", kind: "textarea", placeholder: "Cameras, intercoms, access control, gate/door hardware.", visibleWhen: associationVisible },
    { id: "commonAreaSummary", label: "Overall Common Area / Amenities Summary", kind: "textarea", placeholder: "Concise summary of significant observations, deferred maintenance, or safety concerns.", visibleWhen: associationVisible },

    { id: "environmentalDivider", label: "Environmental and Site Feasibility", kind: "divider", placeholder: "Flag observed or known site risks that may affect development, financing, or safety." },
    { id: "soilStability", label: "Soil Quality and Stability Assessment", kind: "select", required: true, options: ["Good (Appears stable, typical quality)", "Fair (Some rock or clay observed)", "Poor (Sand, expansive clay, or swampy. Soil test recommended.)", "Unknown / Not Assessed"], fullWidth: true },
    { id: "soilStabilityExplain", label: "Soil Quality and Stability Assessment Explanation", kind: "textarea", placeholder: "Describe visible soil, slope, fill, rock, clay, swampy areas, or why the condition is unknown." },
    { id: "floodDrainageIssues", label: "Flood Zone or Drainage Issues?", kind: "select", required: true, options: ["Yes (Known Flood Zone or Drainage Issue)", "No (Appears clear)", "Unknown"] },
    { id: "floodDrainageExplain", label: "Flood / Drainage Explanation", kind: "textarea", placeholder: "Note the zone, observed drainage concern, and source if known." },
    { id: "contaminationRisk", label: "Contamination Risks?", kind: "select", required: true, options: ["Yes (High Risk - recommend Phase I)", "Low Risk (Residential area)", "Unknown"] },
    { id: "contaminationExplain", label: "Contamination Risk Explanation", kind: "textarea", placeholder: "Describe risk source, such as adjacent gas station, old industrial use, or waste site." },

    { id: "publicRecordsDivider", label: "Public Records and Compliance", kind: "divider", placeholder: "Good-faith public-record and visible-use observations. Verify with the authority having jurisdiction as needed." },
    { id: "knownLiensEncroachments", label: "Any known liens or encroachments?", kind: "select", options: yesNoUnknownOptions },
    { id: "liensEncroachmentsExplain", label: "Liens / Encroachments Explanation", kind: "textarea", placeholder: "Type of lien/encroachment, source, date, or document number if known." },
    { id: "activeLicenses", label: "Any active licenses on the property?", kind: "select", options: yesNoUnknownOptions },
    { id: "activeLicensesExplain", label: "Active Licenses Explanation", kind: "textarea", placeholder: "Rental license, use and occupancy, business license, etc." },
    { id: "knownViolations", label: "Any known violations on the property?", kind: "select", options: yesNoUnknownOptions },
    { id: "knownViolationsExplain", label: "Violations Explanation", kind: "textarea", placeholder: "Type of violation, notice number/source, approximate date." },
    { id: "knownFloodZone", label: "Is the property within a known Flood Zone?", kind: "select", options: yesNoUnknownOptions },
    { id: "knownFloodZoneExplain", label: "Known Flood Zone Explanation", kind: "textarea", placeholder: "FEMA zone, FIRM/MSC source, panel/date if known." },

    { id: "siteConditionDivider", label: "Site Condition", kind: "divider", placeholder: "Summarize the observed condition of the vacant lot and grounds." },
    { id: "overallConditionRating", label: "Overall Site Condition", kind: "select", required: true, options: ["Build-Ready", "Partially Improved", "Unimproved / Raw"], fullWidth: true },
    { id: "siteGroundsRating", label: "Condition Rating (Site and Grounds)", kind: "select", required: true, options: conditionOptions },
    { id: "siteGroundsExplain", label: "Site and Grounds Explanation", kind: "textarea", placeholder: "Significant overgrowth, debris, poor drainage, retaining walls, fencing, grading, etc." },
    { id: "easementsAccess", label: "Easements / Access", kind: "textarea", placeholder: "Known easements, access limitations, right-of-way, alley access, curb cut, etc." },

    { id: "healthSafetyDivider", label: "Health and Safety", kind: "divider", placeholder: "Capture immediate observed concerns and visible safety issues." },
    { id: "visibleHazards", label: "Visible Hazards?", kind: "select", required: true, options: yesNoNaOptions },
    { id: "visibleHazardsNotes", label: "Visible Hazards Notes", kind: "textarea", placeholder: "Loose steps, missing railings, unsafe entry, debris, exposed utilities, etc." },
    { id: "visibleCodeViolations", label: "Visible Code Violations?", kind: "select", required: true, options: yesNoNaOptions },
    { id: "visibleCodeViolationsNotes", label: "Visible Code Violations Notes", kind: "textarea" },
    { id: "exteriorOdors", label: "Obvious Exterior Odors Present?", kind: "select", required: true, options: yesNoNaOptions },
    { id: "exteriorOdorsNotes", label: "Exterior Odors Notes", kind: "textarea", placeholder: "Industrial, landfill, stagnant water, petroleum, sewer, etc." },
    { id: "healthSafetySummary", label: "Health and Safety Summary", kind: "textarea", placeholder: "Concise summary of any critical concerns, locations, and immediate recommendations." }
  ]
};
